travis:
  secure:
    BINSTAR_TOKEN: BaYOp9+z0pG37oW0gQ8frbx9mbDPKVIT58v/+nM7ERHKNkYr5pnclYyJscZWsqSNw9eqWYCp7V2W8ISR0s9+Pc+AGnGuYAmPPQF266l1RPvbxflEp30uGAqcvCa0Z6gvFypgz+cwV74T1mSFCV4uwirj5S+zREmZDocR70XbclmuP1J67GdU4PIlNhCbnqxAeDDmuAH8nTYHzq9t0uOSCA17Rq1BywZPNKM0F22Qma02+GrGFPZ1isKSx7HkTdPKddXKjWf1F8a0GOmn9oCiAb4lyHPmblK9cS2wNnEb/CnyLk1V7XVGfrIl/4iwkBhs4mSfth64olXw8/v99LaKQXOWkxi4ch9KE2dy6npcaU71eZRDZQ066pJV310Jkl3vvu3Xbjv2vwdrjmk1B20sKPu7QeHh6HN9mUb/2NeY7aRosqYMQUhOnvLbeDxfYvZ9t5c+q1/7pdQwRTzm2cH6sTCBu5uTKIeR/TAy9qLa8rOAC0Cjse3jcEAmq3LPepd3P25sQZGqBz0iJYF/AEGnDIOrQlifYs8HKhWmo1HfgcS7tlY1LZrKkAtyEBwuD3RUD66ChQzGvhWOnSen5TgrQoVXGccSPN90eIKzKgu/6Zz8Nnch7HrmiX527vdrQzPyj9gKkRwxbvkPR9TfSlPvyZDnrfUvrUn96HJhvVejc30=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
